### ISSUE TITLE
Hands and eyes not rendered correctly

### ISSUE THREAD

**Issue by ilyavflaks** [readyplayerme/visage#23]
Hi,
This issue seems to come and go, so it's not always easy to reproduce. Sometimes the <Avatar> component of Visage is rendered with no hands and no eyes. Instead there are two beams coming out of the elbows with hands at the end of them

Setting halfBody to "true" seems to trigger the issue, but it doesn't always go back to normal when  halfBody="true" is subsequently commented out. 

<img width="396" alt="Screenshot 2023-03-08 at 10 01 06 AM" src="https://user-images.githubusercontent.com/126735700/223795416-72cd5f85-7a9a-41ab-807b-19a02c9f891c.png">

https://codesandbox.io/s/youthful-fermi-c5bjgf?file=/src/App.js

**Comment by Zaehiel** [comment]
Hi @ilyavflaks 

`halfBody` prop should only be used for half body avatars - i.e. avatars without torso and hands.
Technically, half body avatars still have hands, which are useful in VR, but don't need to be shown while viewing the avatar, that's why they are displaced and this funky effect occurs.

You can toggle the `halfBody` prop in our [storybook example](https://readyplayerme.github.io/visage/?path=/story/components-avatar--animated) and see similar results.
